camera/horizontal_fov: 90.0
camera/vertical_fov: 90.0
# 3/17, degree = 90.0 in our airsim config

raycast/dr:     0.1
raycast/dphi:   10
raycast/dtheta: 10

system/bbx/r: 1.5 # drone size
#  3/11 10:56, 0.75 orignally, change to 0.5 for testing purpose
#  3/25 09:33, what is the size of our drone?
system/bbx/overshoot: 0.25

aep/gain/r_min: 0
aep/gain/r_max: 5
# 3/17, 5->10
aep/gain/zero: 20
# 3/17, 25 -> 3
aep/gain/lambda: 0.39
# 4/15, high lambda: more local search, low: more exploration.
# 3/17, 0.75 -> 0.25
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 15
aep/tree/max_sampling_radius: 15
aep/tree/initial_iterations: 15
aep/tree/cutoff_iterations: 30

rrt/min_nodes: 100

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
boundary/min: [-100.0, -100.0, 0.0]
boundary/max: [ 100.0,  100.0, 30.0]

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true

robot_frame: "camera_link"
world_frame: "map"

